#!/bin/bash

export NODE_MODULES_PATH='./node_modules'
export NODE_MODULES_BIN="$NODE_MODULES_PATH/.bin"

export PATH="$NODE_MODULES_BIN:$PATH"

export LESS_BIN='lessc'
export COFFEE_BIN='coffee'
export UGLIFYJS_BIN='uglifyjs'
export AUTOPREFIXER_BIN="autoprefixer"
export AUTOPREFIXER_BROWSERS='> 5%, last 7 versions, Firefox ESR, opera 12.1'

source ./venv/py27/bin/activate
