#!/bin/bash
# Adds some node components into the path and activates the virtualenv

export NODE_MODULES_PATH='./node_modules'
export NODE_MODULES_BIN="$NODE_MODULES_PATH/.bin"

export PATH="$NODE_MODULES_BIN:$PATH"

export LESS_BIN='lessc'
export UGLIFYJS_BIN='uglifyjs'

source ./venv/py38/bin/activate
