#!/bin/bash

export NODE_MODULES_PATH='./node_modules'
export NODE_MODULES_BIN="$NODE_MODULES_PATH/.bin"

export PATH="$NODE_MODULES_BIN:$PATH"

export LESS_BIN='lessc'
export COFFEE_BIN='coffee'
export UGLIFYJS_BIN='uglifyjs'

# These are for dusty
export NODE_PATH='node'
export DUSTY_PATH="$NODE_MODULES_BIN/dusty"

source ./venv/py27/bin/activate
